/* Decoder:                                                    HDO, 2025-03-11
   -------
  Decoder for MiniJava bytecode generated by the compiler.
============================================================================*/

public class Decoder {

  private final byte[] ca; // code array
  private int pc; // program counter

  private OpCode fetchOpCode() {
    return OpCode.values()[ca[pc++]];
  } // fetchOpCode

  private int posValOf(byte b) {
    if (b >= 0)
      return b;
    else // b < 0
      return 256 + b;
  } // posValOf

  private int fetchOperand() {
    return posValOf(ca[pc++]) +                  // format: little endian
           posValOf(ca[pc++]) * 256 +
           posValOf(ca[pc++]) * 256 * 256 +
           posValOf(ca[pc++]) * 256 * 256 * 256;
  } // fetchOperand

  public Decoder(byte[] codeArray) {
    this.ca = codeArray;
    pc = 0;
  } // Decoder

  public void decode() {
    IO.println("decoding started ...");
    OpCode opCode;
    pc = 0;
    do {
      IO.print(String.format("%4d: ", pc));
      //System.out.printf("%4d: ", pc);
      opCode = fetchOpCode();
      IO.print(String.format("%-12s ", opCode.toString()));
      //System.out.printf("%-12s ", opCode.toString());
      if (opCode == OpCode.LOAD_CONST ||
          opCode == OpCode.LOAD_VAL   ||
          opCode == OpCode.LOAD_ADDR) {
        int operand = fetchOperand();
        IO.print(String.format("%5d", operand));
        //System.out.printf("%5d", operand);
      } // if
      IO.println();
    } while (opCode != OpCode.END);
    IO.println("... decoding ended");
  } // decode

} // Decoder
