/* VirtualMachine:                                           HDO, 2025-03-11
   --------------
  Interpreter for MiniJava bytecode generated by the compiler.
============================================================================*/

import java.io.*;

public class VirtualMachine {

  private static final int STACK_SIZE  = 10;
  private static final int MEMORY_SIZE = 20;

  private final byte[] ca;                  // code array
  private int   pc  = 0;                    // program "counter" in ca
  private int[] st  = new int[STACK_SIZE];  // evaluation stack
  private int   sp  = -1;                   // stack "pointer" in st
  private int[] mem = new int[MEMORY_SIZE]; // memory for variables

  public VirtualMachine(byte[] codeArray) {
    this.ca = codeArray;
  } // VirtualMachine

  public VirtualMachine(String codeFileName) {
    try { // to read contents for code array from file
      FileInputStream   fis = new FileInputStream(codeFileName);
      ObjectInputStream ois = new ObjectInputStream(fis);
      ca = (byte[])ois.readObject();
      ois.close();
      fis.close();
    } catch (Exception e) {
      throw new RuntimeException(e.getCause());
    } // catch
  } // VirtualMachine

  private void push(int val) {
    if (sp == STACK_SIZE - 1)
      throw new RuntimeException("evaluation stack overflow");
    st[++sp] = val;
  } // push

  private int pop() {
    if (sp < 0)
      throw new RuntimeException("evaluation stack underflow");
    return st[sp--];
  } // pop

  private OpCode fetchOpCode() {
    return OpCode.values()[ca[pc++]];
  } // fetchOpCode

  private int posValOf(byte b) {
    if (b >= 0)
      return b;
    else // b < 0
      return 256 + b;
  } // posValOf

  private int fetchOperand() {
    return posValOf(ca[pc++]) +                  // format: little endian
           posValOf(ca[pc++]) * 256 +
           posValOf(ca[pc++]) * 256 * 256 +
           posValOf(ca[pc++]) * 256 * 256 * 256;
  } // fetchOperand

  private void checkAddr(int addr) {
    if (addr < 0 || addr > MEMORY_SIZE - 1)
      throw new RuntimeException("address out of memory range");
  } // checkAddr

  public void run() {
    OpCode opCode;
    int addr, val, val1, val2;
    IO.println("virtual machine started ...");
    sp = -1;
    pc = 0;
    loop: while (true) {
      opCode = fetchOpCode();
      // IO.println("" + (pc - 1) + ": "+ opCode);
      switch (opCode) {
        case LOAD_CONST: // operand num: numerical literal
          val = fetchOperand();
          push(val);
          break;
        case LOAD_VAL:   // operand addr: address of variable for value to load
          addr = fetchOperand();
          checkAddr(addr);
          push(mem[addr]);
          break;
        case LOAD_ADDR:  // operand addr: address of variable
          addr = fetchOperand();
          checkAddr(addr);
          push(addr);
          break;
        case STORE:
          val  = pop();
          addr = pop(); // addr already checked
          mem[addr] = val;
          break;
        case ADD:
          val2 = pop();
          val1 = pop();
          push(val1 + val2);
          break;
        case SUB:
          val2 = pop();
          val1 = pop();
          push(val1 - val2);
          break;
        case MUL:
          val2 = pop();
          val1 = pop();
          push(val1 * val2);
          break;
        case DIV:
          val2 = pop();
          if (val2 == 0)
            throw new RuntimeException("division by zero attempt");
          val1 = pop();
          push(val1 / val2);
          break;
        case READ:
          IO.print(" > ");
          //val = Input.readInt();
          val = Integer.parseInt(IO.readln());
          push(val);
          break;
        case PRINT:
          val = pop();
          IO.println(val);
          break;
        case END:
          break loop;
      } // switch
    } // while
    IO.println("... virtual machine ended");
  } // run

} // VirtualMachine
